---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: location-app
  labels:
    name: location-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: location-app
  template:
    metadata:
      labels:
        name: location-app
    spec:
      containers:
      - name: location-app
        image: hub.magellancloud.com/pes/location
        imagePullPolicy: Always
        name: location-app
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
      imagePullSecrets:
      - name: magellanregistry
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: location-app
  labels:
    name: location-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP
  selector:
    name: location-app
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: location-app
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: location-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

