spring:
    profiles: standalone
    datasource:
        url: jdbc:mysql://localhost:3306/microservices
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        show-sql: true
server:
    port: 9000
    
--- 

spring: 
    profiles: test
    jpa:
        database: HSQL
        show-sql: true
        hibernate:
            ddl-auto: update
server:
    port: 9001   